#!/usr/bin/env python3
"""
Summarize a large ServerVM workers.log without uploading the raw file.

Inputs:
  1. samples.csv generated by servervm_net_path_monitor.sh
  2. workers.log generated by the same monitor
  3. Android summary.csv generated by android_udp_path_ab.sh (optional but recommended)

Outputs are compact CSV/text files suitable for upload.

Example:
  python3 summarize_workers.py \
      --samples samples.csv \
      --workers workers.log \
      --android-summary summary.csv \
      --out workers_compact
"""

from __future__ import annotations

import argparse
import bisect
import calendar
import csv
import math
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Optional


TIMESTAMP_RE = re.compile(r"^=====\s+(.+?)\s+=====$")


@dataclass
class TrafficWindow:
    index: int
    start_epoch: int
    end_epoch: int
    duration_s: float
    target_inferred: str
    tap_mbps: float
    eth_mbps: float
    tap_pps: float
    eth_pps: float
    tap_drop_delta: int
    eth_drop_delta: int
    round_no: str = ""
    cpu: str = ""
    target: str = ""
    target_ip: str = ""
    cport: str = ""
    android_sender_mbps: str = ""
    android_receiver_mbps: str = ""
    android_loss_pct: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", required=True, type=Path)
    parser.add_argument("--workers", required=True, type=Path)
    parser.add_argument("--android-summary", type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument(
        "--active-threshold-mbps",
        type=float,
        default=100.0,
        help="tap1 RX threshold used to detect an active iperf window",
    )
    parser.add_argument(
        "--worker-margin-seconds",
        type=int,
        default=2,
        help="include worker snapshots this many seconds around each traffic window",
    )
    return parser.parse_args()


def safe_int(value: str) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def safe_float(value: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return math.nan


def read_samples(path: Path, threshold_mbps: float) -> list[TrafficWindow]:
    rows: list[dict[str, str]] = []

    with path.open(newline="", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        required = {
            "epoch",
            "tap_rx_bytes",
            "tap_rx_packets",
            "tap_rx_dropped",
            "eth_tx_bytes",
            "eth_tx_packets",
            "eth_tx_dropped",
        }
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"samples.csv missing columns: {sorted(missing)}")
        rows.extend(reader)

    if len(rows) < 2:
        raise ValueError("samples.csv contains fewer than two data rows")

    deltas: list[dict[str, float]] = []

    for prev, cur in zip(rows, rows[1:]):
        t0 = safe_int(prev["epoch"])
        t1 = safe_int(cur["epoch"])
        dt = t1 - t0
        if dt <= 0:
            continue

        tap_bytes = safe_int(cur["tap_rx_bytes"]) - safe_int(prev["tap_rx_bytes"])
        tap_packets = safe_int(cur["tap_rx_packets"]) - safe_int(prev["tap_rx_packets"])
        tap_drop = safe_int(cur["tap_rx_dropped"]) - safe_int(prev["tap_rx_dropped"])

        eth_bytes = safe_int(cur["eth_tx_bytes"]) - safe_int(prev["eth_tx_bytes"])
        eth_packets = safe_int(cur["eth_tx_packets"]) - safe_int(prev["eth_tx_packets"])
        eth_drop = safe_int(cur["eth_tx_dropped"]) - safe_int(prev["eth_tx_dropped"])

        deltas.append(
            {
                "epoch": t1,
                "dt": dt,
                "tap_bytes": tap_bytes,
                "tap_packets": tap_packets,
                "tap_drop": tap_drop,
                "eth_bytes": eth_bytes,
                "eth_packets": eth_packets,
                "eth_drop": eth_drop,
                "tap_mbps": tap_bytes * 8.0 / dt / 1_000_000.0,
            }
        )

    windows_raw: list[list[dict[str, float]]] = []
    current: list[dict[str, float]] = []

    for row in deltas:
        active = row["tap_mbps"] >= threshold_mbps

        if active:
            current.append(row)
        elif current:
            if sum(x["dt"] for x in current) >= 10:
                windows_raw.append(current)
            current = []

    if current and sum(x["dt"] for x in current) >= 10:
        windows_raw.append(current)

    windows: list[TrafficWindow] = []

    for index, segment in enumerate(windows_raw, start=1):
        duration = sum(x["dt"] for x in segment)
        tap_bytes = sum(x["tap_bytes"] for x in segment)
        eth_bytes = sum(x["eth_bytes"] for x in segment)
        tap_packets = sum(x["tap_packets"] for x in segment)
        eth_packets = sum(x["eth_packets"] for x in segment)

        ratio = eth_bytes / tap_bytes if tap_bytes > 0 else 0.0
        inferred = "pc" if ratio > 0.5 else "servervm"

        # The first delta ending at epoch X covers the interval before X.
        start_epoch = int(segment[0]["epoch"] - segment[0]["dt"])
        end_epoch = int(segment[-1]["epoch"])

        windows.append(
            TrafficWindow(
                index=index,
                start_epoch=start_epoch,
                end_epoch=end_epoch,
                duration_s=duration,
                target_inferred=inferred,
                tap_mbps=tap_bytes * 8.0 / duration / 1_000_000.0,
                eth_mbps=eth_bytes * 8.0 / duration / 1_000_000.0,
                tap_pps=tap_packets / duration,
                eth_pps=eth_packets / duration,
                tap_drop_delta=sum(int(x["tap_drop"]) for x in segment),
                eth_drop_delta=sum(int(x["eth_drop"]) for x in segment),
            )
        )

    return windows


def attach_android_summary(
    windows: list[TrafficWindow], summary_path: Optional[Path]
) -> list[dict[str, str]]:
    if summary_path is None:
        return []

    with summary_path.open(newline="", encoding="utf-8", errors="replace") as f:
        android_rows = list(csv.DictReader(f))

    if len(android_rows) != len(windows):
        print(
            f"WARNING: detected {len(windows)} traffic windows, "
            f"but Android summary has {len(android_rows)} rows. "
            "Rows will be paired by order up to the shorter length."
        )

    for window, row in zip(windows, android_rows):
        window.round_no = row.get("round", "")
        window.cpu = row.get("cpu", "")
        window.target = row.get("target", "")
        window.target_ip = row.get("target_ip", "")
        window.cport = row.get("cport", "")
        window.android_sender_mbps = row.get("sender_mbps", "")
        window.android_receiver_mbps = row.get("receiver_mbps", "")
        window.android_loss_pct = row.get("loss_pct", "")

    return android_rows


def parse_worker_timestamp(text: str) -> datetime:
    formats = (
        "%Y-%m-%d %H:%M:%S",
        "%a %b %d %H:%M:%S %Y",
        "%b %d %H:%M:%S",
    )

    for fmt in formats:
        try:
            parsed = datetime.strptime(text, fmt)
            if fmt == "%b %d %H:%M:%S":
                # Use the current year only as a fallback. The normal monitor
                # format is YYYY-MM-DD HH:MM:SS.
                parsed = parsed.replace(year=datetime.now().year)
            return parsed
        except ValueError:
            pass

    raise ValueError(f"unsupported workers.log timestamp: {text!r}")


def detect_worker_epoch_offset(workers_path: Path, first_sample_epoch: int) -> int:
    """
    workers.log uses ServerVM local date strings, while samples.csv uses epoch.
    Infer the local-time-to-epoch offset automatically.

    The first worker snapshot is normally about 4-6 seconds after the first
    samples.csv row. Rounding to the nearest 15 minutes removes this small
    startup difference and recovers the timezone offset.
    """
    with workers_path.open(encoding="utf-8", errors="replace") as f:
        for line in f:
            match = TIMESTAMP_RE.match(line.strip())
            if not match:
                continue

            dt = parse_worker_timestamp(match.group(1))
            naive_as_utc = calendar.timegm(dt.timetuple())
            raw_offset = first_sample_epoch - naive_as_utc

            quantum = 15 * 60
            rounded = int(round(raw_offset / quantum) * quantum)
            return rounded

    raise ValueError("workers.log contains no timestamp markers")


def worker_category(comm: str, args: str) -> str:
    text = f"{comm} {args}".lower()

    if "ksoftirqd" in text:
        return "ksoftirqd"
    if "vhost" in text:
        return "vhost"
    if "dsm" in text or "vtnet" in text or "virtio" in text:
        return "dsm"
    return "other"


def choose_interesting_windows(windows: list[TrafficWindow]) -> set[int]:
    pc_windows = [
        w
        for w in windows
        if (w.target or w.target_inferred) == "pc"
        and not math.isnan(safe_float(w.android_receiver_mbps))
    ]

    selected: set[int] = set()

    if pc_windows:
        ordered = sorted(pc_windows, key=lambda w: safe_float(w.android_receiver_mbps))
        selected.update(w.index for w in ordered[:2])
        selected.update(w.index for w in ordered[-2:])

    by_cpu: dict[str, list[TrafficWindow]] = defaultdict(list)
    for w in pc_windows:
        by_cpu[w.cpu].append(w)

    max_spread = -1.0
    spread_windows: tuple[TrafficWindow, TrafficWindow] | None = None

    for cpu_windows in by_cpu.values():
        if len(cpu_windows) < 2:
            continue
        low = min(cpu_windows, key=lambda w: safe_float(w.android_receiver_mbps))
        high = max(cpu_windows, key=lambda w: safe_float(w.android_receiver_mbps))
        spread = safe_float(high.android_receiver_mbps) - safe_float(
            low.android_receiver_mbps
        )
        if spread > max_spread:
            max_spread = spread
            spread_windows = (low, high)

    if spread_windows:
        selected.update(w.index for w in spread_windows)

    # Include the matching local path for CPUs represented in selected PC cases.
    selected_cpus = {w.cpu for w in windows if w.index in selected and w.cpu}
    for cpu in selected_cpus:
        local_cases = [
            w
            for w in windows
            if w.cpu == cpu and (w.target or w.target_inferred) == "servervm"
        ]
        if local_cases:
            selected.add(local_cases[0].index)

    return selected


def find_window(
    epoch: int,
    windows: list[TrafficWindow],
    starts: list[int],
    margin: int,
) -> Optional[TrafficWindow]:
    pos = bisect.bisect_right(starts, epoch) - 1

    for candidate in (pos, pos + 1):
        if candidate < 0 or candidate >= len(windows):
            continue
        window = windows[candidate]
        if window.start_epoch - margin <= epoch <= window.end_epoch + margin:
            return window

    return None


def write_traffic_windows(path: Path, windows: list[TrafficWindow]) -> None:
    fields = [
        "window",
        "start_epoch",
        "end_epoch",
        "start_utc",
        "end_utc",
        "duration_s",
        "round",
        "cpu",
        "target",
        "target_inferred",
        "target_ip",
        "cport",
        "android_sender_mbps",
        "android_receiver_mbps",
        "android_loss_pct",
        "tap_rx_mbps",
        "eth_tx_mbps",
        "tap_rx_pps",
        "eth_tx_pps",
        "tap_drop_delta",
        "eth_drop_delta",
    ]

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()

        for w in windows:
            writer.writerow(
                {
                    "window": w.index,
                    "start_epoch": w.start_epoch,
                    "end_epoch": w.end_epoch,
                    "start_utc": datetime.fromtimestamp(
                        w.start_epoch, timezone.utc
                    ).strftime("%Y-%m-%d %H:%M:%S"),
                    "end_utc": datetime.fromtimestamp(
                        w.end_epoch, timezone.utc
                    ).strftime("%Y-%m-%d %H:%M:%S"),
                    "duration_s": f"{w.duration_s:.3f}",
                    "round": w.round_no,
                    "cpu": w.cpu,
                    "target": w.target,
                    "target_inferred": w.target_inferred,
                    "target_ip": w.target_ip,
                    "cport": w.cport,
                    "android_sender_mbps": w.android_sender_mbps,
                    "android_receiver_mbps": w.android_receiver_mbps,
                    "android_loss_pct": w.android_loss_pct,
                    "tap_rx_mbps": f"{w.tap_mbps:.3f}",
                    "eth_tx_mbps": f"{w.eth_mbps:.3f}",
                    "tap_rx_pps": f"{w.tap_pps:.3f}",
                    "eth_tx_pps": f"{w.eth_pps:.3f}",
                    "tap_drop_delta": w.tap_drop_delta,
                    "eth_drop_delta": w.eth_drop_delta,
                }
            )


def process_workers(
    workers_path: Path,
    windows: list[TrafficWindow],
    epoch_offset: int,
    margin: int,
    selected_windows: set[int],
    out_dir: Path,
) -> None:
    starts = [w.start_epoch for w in windows]

    # Per-window/per-thread statistics.
    thread_stats: dict[tuple[int, int, str], dict] = {}
    category_snapshot_totals: dict[tuple[int, int, str], float] = defaultdict(float)
    category_snapshot_cpus: dict[tuple[int, int, str], set[int]] = defaultdict(set)
    category_snapshots: dict[tuple[int, str], set[int]] = defaultdict(set)

    changes: list[dict[str, str | int | float]] = []
    last_cpu: dict[tuple[int, str], int] = {}

    compact_path = out_dir / "selected_workers.log"
    compact = compact_path.open("w", encoding="utf-8")

    current_epoch: Optional[int] = None
    current_timestamp_text = ""
    current_window: Optional[TrafficWindow] = None
    snapshot_id = 0
    wrote_selected_header = False

    with workers_path.open(encoding="utf-8", errors="replace") as f:
        for raw_line in f:
            stripped = raw_line.strip()
            timestamp_match = TIMESTAMP_RE.match(stripped)

            if timestamp_match:
                snapshot_id += 1
                current_timestamp_text = timestamp_match.group(1)
                dt = parse_worker_timestamp(current_timestamp_text)
                naive_as_utc = calendar.timegm(dt.timetuple())
                current_epoch = naive_as_utc + epoch_offset
                current_window = find_window(
                    current_epoch, windows, starts, margin
                )

                wrote_selected_header = False
                if current_window and current_window.index in selected_windows:
                    compact.write(raw_line)
                    wrote_selected_header = True
                continue

            if current_epoch is None or current_window is None:
                continue

            parts = stripped.split(None, 5)
            if len(parts) < 5 or not parts[0].isdigit() or not parts[1].isdigit():
                continue

            try:
                pid = int(parts[0])
                tid = int(parts[1])
                psr = int(parts[2])
                pcpu = float(parts[3])
            except ValueError:
                continue

            comm = parts[4]
            args = parts[5] if len(parts) >= 6 else ""
            category = worker_category(comm, args)

            if category == "other":
                continue

            if current_window.index in selected_windows:
                if not wrote_selected_header:
                    compact.write(
                        f"===== {current_timestamp_text} =====\n"
                    )
                    wrote_selected_header = True
                compact.write(raw_line)

            key = (current_window.index, tid, comm)
            stat = thread_stats.setdefault(
                key,
                {
                    "window": current_window.index,
                    "pid": pid,
                    "tid": tid,
                    "comm": comm,
                    "category": category,
                    "samples": 0,
                    "pcpu_sum": 0.0,
                    "pcpu_max": 0.0,
                    "cpu_counts": Counter(),
                    "cpu_changes": 0,
                    "first_cpu": psr,
                    "last_cpu": psr,
                    "args": args,
                },
            )

            stat["samples"] += 1
            stat["pcpu_sum"] += pcpu
            stat["pcpu_max"] = max(stat["pcpu_max"], pcpu)
            stat["cpu_counts"][psr] += 1
            stat["last_cpu"] = psr

            change_key = (tid, comm)
            previous = last_cpu.get(change_key)
            if previous is not None and previous != psr:
                stat["cpu_changes"] += 1
                changes.append(
                    {
                        "epoch": current_epoch,
                        "timestamp": current_timestamp_text,
                        "window": current_window.index,
                        "pid": pid,
                        "tid": tid,
                        "comm": comm,
                        "category": category,
                        "old_cpu": previous,
                        "new_cpu": psr,
                        "pcpu": pcpu,
                        "args": args,
                    }
                )
            last_cpu[change_key] = psr

            snap_key = (current_window.index, snapshot_id, category)
            category_snapshot_totals[snap_key] += pcpu
            category_snapshot_cpus[snap_key].add(psr)
            category_snapshots[(current_window.index, category)].add(snapshot_id)

    compact.close()

    thread_fields = [
        "window",
        "round",
        "android_cpu",
        "target",
        "android_receiver_mbps",
        "pid",
        "tid",
        "comm",
        "category",
        "samples",
        "avg_pcpu",
        "max_pcpu",
        "dominant_cpu",
        "first_cpu",
        "last_cpu",
        "cpu_changes",
        "cpu_histogram",
        "args",
    ]

    window_by_index = {w.index: w for w in windows}

    with (out_dir / "worker_threads_by_window.csv").open(
        "w", newline="", encoding="utf-8"
    ) as f:
        writer = csv.DictWriter(f, fieldnames=thread_fields)
        writer.writeheader()

        for stat in sorted(
            thread_stats.values(),
            key=lambda x: (x["window"], x["category"], -x["pcpu_max"], x["tid"]),
        ):
            counts: Counter = stat["cpu_counts"]
            dominant_cpu = counts.most_common(1)[0][0] if counts else ""
            histogram = ";".join(
                f"{cpu}:{count}" for cpu, count in sorted(counts.items())
            )
            w = window_by_index[stat["window"]]

            writer.writerow(
                {
                    "window": stat["window"],
                    "round": w.round_no,
                    "android_cpu": w.cpu,
                    "target": w.target or w.target_inferred,
                    "android_receiver_mbps": w.android_receiver_mbps,
                    "pid": stat["pid"],
                    "tid": stat["tid"],
                    "comm": stat["comm"],
                    "category": stat["category"],
                    "samples": stat["samples"],
                    "avg_pcpu": f"{stat['pcpu_sum'] / stat['samples']:.3f}",
                    "max_pcpu": f"{stat['pcpu_max']:.3f}",
                    "dominant_cpu": dominant_cpu,
                    "first_cpu": stat["first_cpu"],
                    "last_cpu": stat["last_cpu"],
                    "cpu_changes": stat["cpu_changes"],
                    "cpu_histogram": histogram,
                    "args": stat["args"][:300],
                }
            )

    category_fields = [
        "window",
        "round",
        "android_cpu",
        "target",
        "android_receiver_mbps",
        "category",
        "snapshot_count",
        "avg_total_pcpu",
        "max_total_pcpu",
        "cpus_seen",
    ]

    with (out_dir / "worker_categories_by_window.csv").open(
        "w", newline="", encoding="utf-8"
    ) as f:
        writer = csv.DictWriter(f, fieldnames=category_fields)
        writer.writeheader()

        category_keys = sorted(category_snapshots)

        for window_index, category in category_keys:
            snapshots = sorted(category_snapshots[(window_index, category)])
            totals = [
                category_snapshot_totals[(window_index, snap, category)]
                for snap in snapshots
            ]
            cpus: set[int] = set()
            for snap in snapshots:
                cpus.update(
                    category_snapshot_cpus[(window_index, snap, category)]
                )

            w = window_by_index[window_index]
            writer.writerow(
                {
                    "window": window_index,
                    "round": w.round_no,
                    "android_cpu": w.cpu,
                    "target": w.target or w.target_inferred,
                    "android_receiver_mbps": w.android_receiver_mbps,
                    "category": category,
                    "snapshot_count": len(snapshots),
                    "avg_total_pcpu": f"{sum(totals) / len(totals):.3f}",
                    "max_total_pcpu": f"{max(totals):.3f}",
                    "cpus_seen": ";".join(str(x) for x in sorted(cpus)),
                }
            )

    change_fields = [
        "epoch",
        "timestamp",
        "window",
        "round",
        "android_cpu",
        "target",
        "android_receiver_mbps",
        "pid",
        "tid",
        "comm",
        "category",
        "old_cpu",
        "new_cpu",
        "pcpu",
        "args",
    ]

    with (out_dir / "worker_cpu_changes.csv").open(
        "w", newline="", encoding="utf-8"
    ) as f:
        writer = csv.DictWriter(f, fieldnames=change_fields)
        writer.writeheader()

        for change in changes:
            w = window_by_index[int(change["window"])]
            row = dict(change)
            row.update(
                {
                    "round": w.round_no,
                    "android_cpu": w.cpu,
                    "target": w.target or w.target_inferred,
                    "android_receiver_mbps": w.android_receiver_mbps,
                }
            )
            writer.writerow(row)

    with (out_dir / "selected_windows.txt").open(
        "w", encoding="utf-8"
    ) as f:
        f.write(
            "These windows were selected automatically for the compact "
            "workers log.\n\n"
        )
        for index in sorted(selected_windows):
            w = window_by_index[index]
            f.write(
                f"window={w.index} round={w.round_no} cpu={w.cpu} "
                f"target={w.target or w.target_inferred} "
                f"android_receiver={w.android_receiver_mbps}Mbps "
                f"tap={w.tap_mbps:.3f}Mbps eth={w.eth_mbps:.3f}Mbps "
                f"epoch={w.start_epoch}-{w.end_epoch}\n"
            )


def main() -> int:
    args = parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    windows = read_samples(args.samples, args.active_threshold_mbps)
    attach_android_summary(windows, args.android_summary)

    write_traffic_windows(args.out / "traffic_windows.csv", windows)

    selected = choose_interesting_windows(windows)

    with args.samples.open(newline="", encoding="utf-8", errors="replace") as f:
        first_sample = next(csv.DictReader(f))
        first_sample_epoch = safe_int(first_sample["epoch"])

    epoch_offset = detect_worker_epoch_offset(args.workers, first_sample_epoch)

    process_workers(
        args.workers,
        windows,
        epoch_offset,
        args.worker_margin_seconds,
        selected,
        args.out,
    )

    with (args.out / "summary.txt").open("w", encoding="utf-8") as f:
        f.write(f"traffic_windows={len(windows)}\n")
        f.write(f"worker_epoch_offset_seconds={epoch_offset}\n")
        f.write(
            "selected_windows="
            + ",".join(str(x) for x in sorted(selected))
            + "\n"
        )
        f.write("\nUpload these files first:\n")
        f.write("  traffic_windows.csv\n")
        f.write("  worker_categories_by_window.csv\n")
        f.write("  worker_cpu_changes.csv\n")
        f.write("  selected_windows.txt\n")
        f.write("  selected_workers.log\n")
        f.write("\nIf needed later:\n")
        f.write("  worker_threads_by_window.csv\n")

    print(f"Done. Compact outputs: {args.out}")
    print("Upload these first:")
    print(f"  {args.out / 'traffic_windows.csv'}")
    print(f"  {args.out / 'worker_categories_by_window.csv'}")
    print(f"  {args.out / 'worker_cpu_changes.csv'}")
    print(f"  {args.out / 'selected_windows.txt'}")
    print(f"  {args.out / 'selected_workers.log'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
